server:
  port: 8498

spring:
  datasource:
    name: dev
    url: jdbc:mysql://127.0.0.1:3306/query_all?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
